# Generated by Django 4.0.1 on 2022-02-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(default='NoNameProduct', max_length=250),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
