# Generated by Django 4.0.1 on 2022-02-17 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='avg_rating',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'recipe')},
        ),
    ]
