# Generated by Django 4.0.1 on 2022-02-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0002_remove_ingredient_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='recipe_id',
            new_name='recipe',
        ),
    ]
