# Generated by Django 4.0.1 on 2022-02-17 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0002_remove_recipe_avg_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Category', max_length=250)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_recipe', to='food4life.recipe')),
                ('to_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_recipe', to='food4life.recipe')),
            ],
            options={
                'unique_together': {('from_recipe', 'to_recipe')},
            },
        ),
    ]
