# Generated by Django 4.0.1 on 2022-02-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0003_categories_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
    ]
