# Generated by Django 4.0.1 on 2022-02-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0004_alter_recipe_img_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
