# Generated by Django 4.0.1 on 2022-02-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0004_remove_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food4life.recipe'),
        ),
    ]
