# Generated by Django 4.0.1 on 2022-02-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0005_recipe_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
