# Generated by Django 4.0.1 on 2022-02-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food4life', '0006_alter_recipe_calories_alter_recipe_carbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='yields',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
